"""empty message

Revision ID: 14c00bb07d5b
Revises: 87bb0b233c87
Create Date: 2021-03-10 18:25:03.814071

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14c00bb07d5b'
down_revision = '87bb0b233c87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('fundation_name', sa.String(length=200), nullable=False))
    op.drop_constraint('user_fadation_name_key', 'user', type_='unique')
    op.create_unique_constraint(None, 'user', ['fundation_name'])
    op.drop_column('user', 'fadation_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('fadation_name', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'user', type_='unique')
    op.create_unique_constraint('user_fadation_name_key', 'user', ['fadation_name'])
    op.drop_column('user', 'fundation_name')
    # ### end Alembic commands ###
