"""empty message

Revision ID: 1c858cd18b1e
Revises: fd9f009bee6a
Create Date: 2021-03-09 21:38:19.380001

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c858cd18b1e'
down_revision = 'fd9f009bee6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pets', 'color_hair')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pets', sa.Column('color_hair', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
