"""empty message

Revision ID: 284eaf44877d
Revises: 6548ded9a582
Create Date: 2021-03-11 23:18:37.042920

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '284eaf44877d'
down_revision = '6548ded9a582'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pets', sa.Column('imageURL', sa.String(length=2000), nullable=False))
    op.drop_column('pets', 'formData')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pets', sa.Column('formData', sa.VARCHAR(length=2000), autoincrement=False, nullable=False))
    op.drop_column('pets', 'imageURL')
    # ### end Alembic commands ###
