"""empty message

Revision ID: 3cf3dc9b742a
Revises: 
Create Date: 2021-03-11 20:51:24.996613

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3cf3dc9b742a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(length=200), nullable=False),
    sa.Column('fundation_name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=300), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('province', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('fundation_name'),
    sa.UniqueConstraint('phone_number'),
    sa.UniqueConstraint('user_name')
    )
    op.create_table('cats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('fundation_worker', sa.String(length=120), nullable=False),
    sa.Column('descripcition', sa.String(length=2000), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('temperament', sa.String(length=2000), nullable=False),
    sa.Column('vaccines', sa.Boolean(), nullable=False),
    sa.Column('gender', sa.String(length=80), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('fundation_name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=False),
    sa.Column('edad', sa.Integer(), nullable=False),
    sa.Column('tamaño', sa.Integer(), nullable=False),
    sa.Column('temperamento', sa.String(length=2000), nullable=False),
    sa.Column('vacunas', sa.Boolean(), nullable=False),
    sa.Column('sexo', sa.String(length=80), nullable=False),
    sa.Column('pet_name', sa.String(length=2000), nullable=False),
    sa.Column('user_name', sa.String(length=2000), nullable=False),
    sa.Column('phone_number', sa.Integer(), nullable=False),
    sa.Column('pet', sa.String(length=2000), nullable=False),
    sa.Column('province', sa.String(length=2000), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pets')
    op.drop_table('cats')
    op.drop_table('user')
    # ### end Alembic commands ###
