"""empty message

Revision ID: 6548ded9a582
Revises: 3cf3dc9b742a
Create Date: 2021-03-11 22:31:49.373364

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6548ded9a582'
down_revision = '3cf3dc9b742a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pets', sa.Column('formData', sa.String(length=2000), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pets', 'formData')
    # ### end Alembic commands ###
