"""empty message

Revision ID: 87bb0b233c87
Revises: 1c858cd18b1e
Create Date: 2021-03-09 21:43:25.534227

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87bb0b233c87'
down_revision = '1c858cd18b1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pets', sa.Column('temperament', sa.String(length=2000), nullable=False))
    op.drop_column('pets', 'cheer_up')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pets', sa.Column('cheer_up', sa.VARCHAR(length=2000), autoincrement=False, nullable=False))
    op.drop_column('pets', 'temperament')
    # ### end Alembic commands ###
