"""empty message

Revision ID: fd9f009bee6a
Revises: 30fb1b056366
Create Date: 2021-03-09 20:31:50.434532

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd9f009bee6a'
down_revision = '30fb1b056366'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('pet_type', sa.String(length=120), nullable=False),
    sa.Column('foundation_worker', sa.String(length=120), nullable=False),
    sa.Column('descripcition', sa.String(length=2000), nullable=False),
    sa.Column('color_hair', sa.String(length=80), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('cheer_up', sa.String(length=2000), nullable=False),
    sa.Column('vaccines', sa.Boolean(), nullable=False),
    sa.Column('gender', sa.String(length=80), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('user', sa.Column('fadation_name', sa.String(length=200), nullable=False))
    op.add_column('user', sa.Column('phone_number', sa.String(length=20), nullable=False))
    op.add_column('user', sa.Column('province', sa.String(length=20), nullable=False))
    op.add_column('user', sa.Column('user_name', sa.String(length=200), nullable=False))
    op.create_unique_constraint(None, 'user', ['phone_number'])
    op.create_unique_constraint(None, 'user', ['fadation_name'])
    op.create_unique_constraint(None, 'user', ['user_name'])
    op.drop_column('user', 'is_active')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'user_name')
    op.drop_column('user', 'province')
    op.drop_column('user', 'phone_number')
    op.drop_column('user', 'fadation_name')
    op.drop_table('pets')
    # ### end Alembic commands ###
